from __future__ import annotations

import argparse
import re
from datetime import datetime, timezone
from decimal import Decimal

from pyspark.sql import SparkSession
from pyspark.sql.types import (
    DecimalType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)


MAKES = [
    (1, "Toyota", "Japan", 1937),
    (2, "Honda", "Japan", 1948),
    (3, "Ford", "United States", 1903),
    (4, "Tesla", "United States", 2003),
    (5, "BMW", "Germany", 1916),
]

MODELS = [
    (101, 1, "Camry", "Sedan", 2025, Decimal("28400.00")),
    (102, 1, "RAV4", "SUV", 2025, Decimal("29100.00")),
    (201, 2, "Civic", "Sedan", 2025, Decimal("24700.00")),
    (202, 2, "CR-V", "SUV", 2025, Decimal("30400.00")),
    (301, 3, "Mustang", "Coupe", 2025, Decimal("31920.00")),
    (302, 3, "F-150", "Truck", 2025, Decimal("38500.00")),
    (401, 4, "Model 3", "Sedan", 2025, Decimal("42490.00")),
    (402, 4, "Model Y", "SUV", 2025, Decimal("44990.00")),
    (501, 5, "3 Series", "Sedan", 2025, Decimal("45950.00")),
    (502, 5, "X3", "SUV", 2025, Decimal("50000.00")),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Refresh two governed car reference tables.")
    parser.add_argument("--catalog", required=True)
    parser.add_argument("--schema", required=True)
    parser.add_argument("--project-id", required=True)
    parser.add_argument("--environment", required=True, choices=("dev", "prod"))
    return parser.parse_args()


def safe_identifier(value: str, label: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", value):
        raise ValueError(f"{label} must contain only letters, digits, and underscores: {value!r}")
    return value


def quoted(value: str) -> str:
    return f"`{value}`"


def main() -> None:
    args = parse_args()
    catalog = safe_identifier(args.catalog, "catalog")
    schema = safe_identifier(args.schema, "schema")
    project_id = args.project_id.strip()
    if not re.fullmatch(r"PRJ-[A-Z0-9]{10}", project_id):
        raise ValueError("project-id must be the PRJ-* identifier generated by the Registry App.")

    spark = SparkSession.getActiveSession() or SparkSession.builder.getOrCreate()
    loaded_at = datetime.now(timezone.utc)

    spark.sql(
        f"CREATE SCHEMA IF NOT EXISTS {quoted(catalog)}.{quoted(schema)} "
        "COMMENT 'Governed schema for the car reference ETL demonstration'"
    )

    makes_schema = StructType(
        [
            StructField("make_id", IntegerType(), False),
            StructField("make_name", StringType(), False),
            StructField("country", StringType(), False),
            StructField("founded_year", IntegerType(), False),
            StructField("project_id", StringType(), False),
            StructField("environment", StringType(), False),
            StructField("loaded_at", TimestampType(), False),
        ]
    )
    makes_rows = [(*row, project_id, args.environment, loaded_at) for row in MAKES]
    makes_df = spark.createDataFrame(makes_rows, makes_schema)

    models_schema = StructType(
        [
            StructField("model_id", IntegerType(), False),
            StructField("make_id", IntegerType(), False),
            StructField("model_name", StringType(), False),
            StructField("vehicle_type", StringType(), False),
            StructField("model_year", IntegerType(), False),
            StructField("starting_msrp_usd", DecimalType(12, 2), False),
            StructField("project_id", StringType(), False),
            StructField("environment", StringType(), False),
            StructField("loaded_at", TimestampType(), False),
        ]
    )
    models_rows = [(*row, project_id, args.environment, loaded_at) for row in MODELS]
    models_df = spark.createDataFrame(models_rows, models_schema)

    makes_table = f"{catalog}.{schema}.car_makes"
    models_table = f"{catalog}.{schema}.car_models"

    (
        makes_df.write.format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(makes_table)
    )
    (
        models_df.write.format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(models_table)
    )

    make_count = spark.table(makes_table).count()
    model_count = spark.table(models_table).count()
    orphan_count = spark.sql(
        f"""
        SELECT COUNT(*) AS count
        FROM {quoted(catalog)}.{quoted(schema)}.{quoted('car_models')} m
        LEFT ANTI JOIN {quoted(catalog)}.{quoted(schema)}.{quoted('car_makes')} k
          ON m.make_id = k.make_id
        """
    ).first()["count"]

    if make_count != len(MAKES):
        raise RuntimeError(f"Expected {len(MAKES)} car makes, found {make_count}.")
    if model_count != len(MODELS):
        raise RuntimeError(f"Expected {len(MODELS)} car models, found {model_count}.")
    if orphan_count != 0:
        raise RuntimeError(f"Found {orphan_count} car model rows without a matching make.")

    print(
        f"Refreshed {makes_table} ({make_count} rows) and "
        f"{models_table} ({model_count} rows) for {project_id}/{args.environment}."
    )


if __name__ == "__main__":
    main()
